server {
    listen 80;
    
    # Root directory set ki
    root /usr/share/nginx/html;
    index index.html index.htm;

    # NAYA CHANGE: Static assets (jaise JS, CSS, images) ko cache hone do taki site fast load ho
    location /assets {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Main location block
    location / {
        try_files $uri $uri/ /index.html;
        
        # NAYA CHANGE: index.html ko browser me cache hone se rokne ke liye
        add_header Cache-Control "no-store, no-cache, must-revalidate";
    }
}