version: '3.8'

services:
  backend:
    build: ./Backend  # Yahan 'B' capital kar do kyunki tumhare folder ka naam 'Backend' hai
    ports:
      - "5000:5000"
    restart: always

  frontend:
    build: ./frontend # Isko 'frontend' hi rehne do agar folder small 'f' se hai
    ports:
      - "80:80"       # Yahan 5173 hata kar 80 kar diya hai
    depends_on:
      - backend
    restart: always